# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
name = "About Me"
pageRef = "aboutme"
weight = -2

[[main]]
name = "Projects"
pageRef = "projects"
weight = 10

[[main]]
name = "Game Development"
parent = "Projects"
pageRef = "examples"
weight = 30

[[main]]
name = "Web Development"
parent = "Projects"
pageRef = "guides"
weight = 40

[[main]]
name = "Blog"
weight = 20

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/Gabriel-Spinola/gabriel-spinola.github.io"
weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10
